### ISSUE TITLE
关于农行支付的请求支付页面的问题

### ISSUE THREAD

**Issue by Newdxz** [wenzhucjy/GeneralUtils#2]
在您accessGateWay方法中有一个参数 resultNotifyUrl 服务器通知URL,公网能访问的地址，而且端口号必须为 80 或者 443（http 默认端口为 80；https 默认端口为 443）   请问这个参数是具体干嘛用的呢？ 我有点不太懂，能帮忙解释一下吗？

**Comment by wenzhucjy** [comment]
支付成功后农行发起的通知，使用POST方式，服务这边需要传递一个参数resultNotifyUrl 告知银行，这个地址必须是公网能访问的地址

**Comment by wenzhucjy** [comment]
> 支付成功后农行发起的通知，使用POST方式，服务这边需要传递一个参数resultNotifyUrl 告知银行，这个地址必须是公网能访问的地址



> 在您accessGateWay方法中有一个参数 resultNotifyUrl 服务器通知URL,公网能访问的地址，而且端口号必须为 80 或者 443（http 默认端口为 80；https 默认端口为 443） 请问这个参数是具体干嘛用的呢？ 我有点不太懂，能帮忙解释一下吗？

支付成功后农行发起的通知，使用POST方式，服务这边需要传递一个参数resultNotifyUrl 告知银行，这个地址必须是公网能访问的地址，服务这边接口到银行请求，验证参数并处理对应的业务

**Comment by wenzhucjy** [comment]
> 在您accessGateWay方法中有一个参数 resultNotifyUrl 服务器通知URL,公网能访问的地址，而且端口号必须为 80 或者 443（http 默认端口为 80；https 默认端口为 443） 请问这个参数是具体干嘛用的呢？ 我有点不太懂，能帮忙解释一下吗？

支付成功后农行发起的通知，使用POST方式，服务这边需要传递一个参数resultNotifyUrl 告知银行，这个地址必须是公网能访问的地址，服务这边接口到银行请求，验证参数并处理对应的业务
